SELECT
    toDateTime(time_bucket) AS time_bucket,
    realm,
    coalesce(league, '') AS league,
    concat(category, ':set') AS item_or_market_key,
    concat(category, ':set') AS semantic_key,
    toFloat64(listing_count) * 0.06 AS expected_profit_chaos,
    if(distinct_base_types > 0, toFloat64(listing_count) / toFloat64(distinct_base_types), 0.0) AS expected_roi,
    least(1.0, toFloat64(distinct_base_types) / 20.0) AS confidence,
    listing_count AS sample_count,
    3 AS estimated_operations,
    6 AS estimated_whispers,
    greatest(0.0, least(1.0, toFloat64(listing_count) / greatest(toFloat64(distinct_base_types) * 5.0, 1.0))) AS liquidity_score,
    greatest(0, dateDiff('minute', toDateTime(updated_at), now())) AS staleness_minutes,
    'Map/logbook package depth stays scarce across base types' AS why_it_fired,
    'Buy map/logbook bundles before coverage expands' AS buy_plan,
    'Rotate buys within the same category until distinct bases grow' AS transform_plan,
    'Exit once distinct base breadth surpasses 20 or listing depth rebounds' AS exit_plan,
    '3h' AS expected_hold_time,
    category,
    distinct_base_types,
    listing_count,
    updated_at
FROM poe_trade.gold_set_ref_hour
WHERE category IN ('map', 'logbook');
