SELECT
    toDateTime(time_bucket) AS time_bucket,
    realm,
    coalesce(league, '') AS league,
    concat(category, ':set') AS item_or_market_key,
    concat(category, ':set') AS semantic_key,
    toFloat64(listing_count) * 0.05 AS expected_profit_chaos,
    if(distinct_base_types > 0, toFloat64(listing_count) / toFloat64(distinct_base_types), 0.0) AS expected_roi,
    least(1.0, toFloat64(distinct_base_types) / 30.0) AS confidence,
    listing_count AS sample_count,
    3 AS estimated_operations,
    5 AS estimated_whispers,
    greatest(0.0, least(1.0, toFloat64(listing_count) / greatest(toFloat64(distinct_base_types) * 4.0, 1.0))) AS liquidity_score,
    greatest(0, dateDiff('minute', toDateTime(updated_at), now())) AS staleness_minutes,
    'Fragment set supply remains limited relative to listing depth' AS why_it_fired,
    'Build fragment inventories while base type breadth stays below 30' AS buy_plan,
    'Layer orders across fragment categories and rotate bases as depth grows' AS transform_plan,
    'Exit when distinct base coverage expands or listing depth normalizes' AS exit_plan,
    '2h' AS expected_hold_time,
    category,
    distinct_base_types,
    listing_count,
    updated_at
FROM poe_trade.gold_set_ref_hour
WHERE category = 'other';
