SELECT
    time_bucket AS time_bucket,
    coalesce(realm, '') AS realm,
    coalesce(league, '') AS league,
    concat(category, ':reroll') AS item_or_market_key,
    concat(category, ':reroll') AS semantic_key,
    (coalesce(median_small_price_amount, 0.0) - coalesce(median_bulk_price_amount, 0.0)) * toFloat64(bulk_threshold) AS expected_profit_chaos,
    if(coalesce(median_bulk_price_amount, 0.0) > 0.0, (coalesce(median_small_price_amount, 0.0) - coalesce(median_bulk_price_amount, 0.0)) / coalesce(median_bulk_price_amount, 0.0), 0.0) AS expected_roi,
    least(1.0, toFloat64(bulk_listing_count) / 50.0) AS confidence,
    bulk_listing_count AS sample_count,
    3 AS estimated_operations,
    6 AS estimated_whispers,
    greatest(0.0, least(1.0, toFloat64(bulk_listing_count) / greatest(toFloat64(small_listing_count), 1.0))) AS liquidity_score,
    greatest(0, dateDiff('minute', toDateTime(time_bucket), now())) AS staleness_minutes,
    'Scarab reroll spread between bulk and small lots' AS why_it_fired,
    'Buy bulk scarabs to reroll while small price premium stays wide' AS buy_plan,
    'Add to reroll queue until small listings compress under the reroll budget' AS transform_plan,
    'Exit when rerolled scarabs trade near bulk threshold or bulk price drops' AS exit_plan,
    '1.5h' AS expected_hold_time,
    category,
    bulk_threshold,
    bulk_listing_count,
    small_listing_count,
    median_bulk_price_amount,
    median_small_price_amount
FROM poe_trade.gold_bulk_premium_hour
WHERE category = 'scarab';
