"""Shared runtime constants for PoE ledger services."""

SERVICE_NAMES = [
    "market_harvester",
    "scanner_worker",
    "ml_trainer",
    "poeninja_snapshot",
    "api",
]
OPTIONAL_SERVICES: list[str] = []
INGEST_CONTRACT_VERSION = 2
LEGACY_RECOMMENDATION_CONTRACT_VERSION = 1
RECOMMENDATION_CONTRACT_VERSION = 3
DEFAULT_RECOMMENDATION_SOURCE = "strategy_pack"
FEED_KIND_PSAPI = "psapi"
FEED_KIND_CXAPI = "cxapi"
FEED_KIND_ACCOUNT_STASH = "account_stash"
QUEUE_KEY_SEPARATOR = ":"
QUEUE_PREFIXES = {
    FEED_KIND_PSAPI: f"{FEED_KIND_PSAPI}{QUEUE_KEY_SEPARATOR}",
    FEED_KIND_CXAPI: f"{FEED_KIND_CXAPI}{QUEUE_KEY_SEPARATOR}",
    FEED_KIND_ACCOUNT_STASH: f"{FEED_KIND_ACCOUNT_STASH}{QUEUE_KEY_SEPARATOR}",
}
DEFAULT_REALMS = ["pc"]
DEFAULT_LEAGUES = ["Synthesis"]
DEFAULT_TIME_BUCKETS = ["1h", "6h", "24h"]
DEFAULT_THRESHOLDS = {
    "min_listing_count": 5,
    "max_price_spread": 0.25,
    "session_profit_min": 0.1,
}
DEFAULT_CHAOS_CURRENCY = "chaos"
DEFAULT_CLICKHOUSE_URL = "http://clickhouse:8123"
DEFAULT_SERVICE_PORTS: dict[str, int] = {}


DEFAULT_POE_API_BASE_URL = "https://api.pathofexile.com"
DEFAULT_POE_AUTH_BASE_URL = "https://www.pathofexile.com/oauth"
DEFAULT_POE_USER_AGENT = "poe-trade/0.1"
DEFAULT_RATE_LIMIT_MAX_RETRIES = 3
DEFAULT_RATE_LIMIT_BACKOFF_BASE = 1.0
DEFAULT_RATE_LIMIT_BACKOFF_MAX = 30.0
DEFAULT_RATE_LIMIT_JITTER = 0.5
DEFAULT_POE_REQUEST_TIMEOUT = 30.0
DEFAULT_CHECKPOINT_DIR = "/tmp/poe_trade/checkpoints"
DEFAULT_MARKET_POLL_INTERVAL = 0.5
DEFAULT_STASH_POLL_INTERVAL = 300.0
DEFAULT_ENABLE_PSAPI = True
DEFAULT_ENABLE_CXAPI = False
DEFAULT_PSAPI_POLL_SECONDS = 30.0
DEFAULT_CXAPI_BACKFILL_HOURS = 168
DEFAULT_CXAPI_HOUR_OFFSET_SECONDS = 15
DEFAULT_REFRESH_REFS_MINUTES = 5
DEFAULT_SCAN_MINUTES = 5
DEFAULT_RAW_PSAPI_TTL_DAYS = 21
DEFAULT_RAW_CX_TTL_DAYS = 365
DEFAULT_SILVER_TTL_DAYS = 90
DEFAULT_STASH_TRIGGER_TOKEN = ""
DEFAULT_OAUTH_GRANT_TYPE = "client_credentials"
DEFAULT_OAUTH_SCOPE = "service:psapi"
DEFAULT_POE_STASH_API_PATH = "public-stash-tabs"
DEFAULT_STASH_BOOTSTRAP_UNTIL_LEAGUE = ""
DEFAULT_STASH_BOOTSTRAP_FROM_BEGINNING = False
DEFAULT_API_BIND_HOST = "127.0.0.1"
DEFAULT_API_BIND_PORT = 8080
DEFAULT_API_OPERATOR_TOKEN = ""
DEFAULT_API_CORS_ORIGINS: tuple[str, ...] = ("https://poe.lama-lan.ch",)
DEFAULT_API_TRUSTED_ORIGIN_BYPASS = False
DEFAULT_API_MAX_BODY_BYTES = 32768
DEFAULT_API_LEAGUE_ALLOWLIST = ("Mirage",)
DEFAULT_ENABLE_ACCOUNT_STASH = False
DEFAULT_ACCOUNT_STASH_REALM = "pc"
DEFAULT_ACCOUNT_STASH_LEAGUE = "Mirage"
DEFAULT_AUTH_STATE_DIR = ".sisyphus/state/auth"
DEFAULT_AUTH_COOKIE_NAME = "poe_session"
DEFAULT_AUTH_COOKIE_SECURE = False
DEFAULT_POE_ACCOUNT_OAUTH_AUTHORIZE_URL = "https://www.pathofexile.com/oauth/authorize"
DEFAULT_POE_ACCOUNT_OAUTH_TOKEN_URL = "https://www.pathofexile.com/oauth/token"
DEFAULT_POE_ACCOUNT_OAUTH_REVOKE_URL = "https://www.pathofexile.com/oauth/token/revoke"
DEFAULT_POE_ACCOUNT_OAUTH_SCOPE = "account:profile account:stashes"
DEFAULT_POE_ACCOUNT_REDIRECT_URI = ""
DEFAULT_POE_ACCOUNT_FRONTEND_COMPLETE_URI = "https://poe.lama-lan.ch/auth/callback"
DEFAULT_ML_AUTOMATION_LEAGUE = "Mirage"
DEFAULT_ML_AUTOMATION_ENABLED = True
DEFAULT_ML_AUTOMATION_INTERVAL_SECONDS = 600
DEFAULT_ML_AUTOMATION_MAX_ITERATIONS = 1
DEFAULT_ML_AUTOMATION_MAX_WALL_CLOCK_SECONDS = 900
DEFAULT_ML_AUTOMATION_NO_IMPROVEMENT_PATIENCE = 2
DEFAULT_ML_AUTOMATION_MIN_MDAPE_IMPROVEMENT = 0.005
DEFAULT_POE_ENABLE_POENINJA_SNAPSHOT = True
DEFAULT_POE_POENINJA_SNAPSHOT_LEAGUE = None
DEFAULT_POE_ML_DATASET_REBUILD_INTERVAL_SECONDS = 3600
