SELECT
    time_bucket AS time_bucket,
    coalesce(realm, '') AS realm,
    coalesce(league, '') AS league,
    concat(category, ':scarcity') AS item_or_market_key,
    concat(category, ':scarcity') AS semantic_key,
    (coalesce(median_small_price_amount, 0.0) - coalesce(median_bulk_price_amount, 0.0)) * toFloat64(small_listing_count) * 0.02 AS expected_profit_chaos,
    if(coalesce(median_bulk_price_amount, 0.0) > 0.0, (coalesce(median_small_price_amount, 0.0) - coalesce(median_bulk_price_amount, 0.0)) / coalesce(median_bulk_price_amount, 0.0), 0.0) AS expected_roi,
    least(1.0, toFloat64(small_listing_count) / 80.0) AS confidence,
    small_listing_count AS sample_count,
    3 AS estimated_operations,
    6 AS estimated_whispers,
    greatest(0.0, least(1.0, toFloat64(small_listing_count) / greatest(toFloat64(bulk_listing_count), 1.0))) AS liquidity_score,
    greatest(0, dateDiff('minute', toDateTime(time_bucket), now())) AS staleness_minutes,
    'Fossil scarcity signal from small listing premium' AS why_it_fired,
    'Sample small listings for scarcity and buy the cheapest bulk replacements' AS buy_plan,
    'Layer orders while small count stays low and premium remains healthy' AS transform_plan,
    'Exit when small listing premium collapses or coverage improves' AS exit_plan,
    '3h' AS expected_hold_time,
    category,
    bulk_threshold,
    bulk_listing_count,
    small_listing_count,
    median_bulk_price_amount,
    median_small_price_amount
FROM poe_trade.gold_bulk_premium_hour
WHERE category = 'fossil';
